=== abraxas-labs/voting-ausmittlung-service/src/Voting.Ausmittlung.Ech/Schemas/eCH-0222-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2012 sp1 (http://www.altova.com) von Martin Stingelin (Stingelin Informatik GmbH) bearbeitet -->
<!-- edited with XMLSpy v2012 rel. 2 sp1 (http://www.altova.com) by Martin Stingelin (Stingelin Informatik GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eCH-0222="http://www.ech.ch/xmlns/eCH-0222/1" xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5" xmlns:eCH-0155="http://www.ech.ch/xmlns/eCH-0155/4" targetNamespace="http://www.ech.ch/xmlns/eCH-0222/1" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:annotation>
		<xs:documentation>Ausgabedatum: 16.07.2018</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.ech.ch/xmlns/eCH-0058/5" schemaLocation="http://www.ech.ch/xmlns/eCH-0058/5/eCH-0058-5-0.xsd"/>
	<xs:import namespace="http://www.ech.ch/xmlns/eCH-0155/4" schemaLocation="http://www.ech.ch/xmlns/eCH-0155/4/eCH-0155-4-0.xsd"/>
	<xs:attribute name="minorVersion" type="xs:integer">
		<xs:annotation>
			<xs:documentation>This attribute is used for indicating the minor version of an XML Schema instance in a standardized way. It SHOULD only appear on the document element of XML Schema instances.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:complexType name="reportingBodyType">
		<xs:sequence>
			<xs:element name="reportingBodyIdentification" type="eCH-0155:identifierType"/>
			<xs:element name="creationDateTime" type="xs:dateTime"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="castedVoteType">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="isUnchangedBallotType">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<xs:complexType name="voteRawDataType">
		<xs:sequence>
			<xs:element name="voteIdentification" type="eCH-0155:voteIdentificationType"/>
			<xs:element name="ballotRawData" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ballotIdentification" type="eCH-0155:ballotIdentificationType"/>
						<xs:element name="ballotCasted">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ballotCastedNumber" type="xs:nonNegativeInteger" minOccurs="0"/>
									<xs:element name="questionRawData" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="questionIdentification" type="eCH-0155:questionIdType"/>
												<xs:element name="casted" minOccurs="0">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="castedVote" type="eCH-0222:castedVoteType"/>
															<xs:element name="answerOptionIdentification" type="eCH-0155:answerOptionIdentificationType" minOccurs="0"/>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="electionRawDataType">
		<xs:sequence>
			<xs:element name="electionIdentification" type="eCH-0155:electionIdentificationType"/>
			<xs:element name="ballotRawData" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="listRawData" minOccurs="0">
							<xs:annotation>
								<xs:documentation>mandatory for proportional elections</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="listIdentification" type="eCH-0155:listIdentificationType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ballotPosition" maxOccurs="unbounded">
							<xs:complexType>
								<xs:choice>
									<xs:element name="candidate">
										<xs:complexType>
											<xs:choice>
												<xs:sequence>
													<xs:element name="candidateIdentification" type="eCH-0155:identifierType"/>
													<xs:element name="candidateReferenceOnPosition" type="eCH-0155:candidateReferenceType"/>
												</xs:sequence>
												<xs:element name="writeIn" type="eCH-0155:writeInType"/>
											</xs:choice>
										</xs:complexType>
									</xs:element>
									<xs:element name="isEmpty" type="xs:boolean" default="true"/>
								</xs:choice>
							</xs:complexType>
						</xs:element>
						<xs:element name="isUnchangedBallot" type="eCH-0222:isUnchangedBallotType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rawDataType">
		<xs:sequence>
			<xs:element name="contestIdentification" type="eCH-0155:contestIdentificationType"/>
			<xs:element name="countingCircleRawData" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="countingCircleId" type="eCH-0155:countingCircleIdType"/>
						<xs:element name="voteRawData" type="eCH-0222:voteRawDataType" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="electionGroupBallotRawData" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="electionGroupIdentification" type="eCH-0155:electionIdentificationType" minOccurs="0"/>
									<xs:element name="electionRawData" type="eCH-0222:electionRawDataType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventRawDataDelivery">
		<xs:sequence>
			<xs:element name="reportingBody" type="eCH-0222:reportingBodyType"/>
			<xs:element name="rawData" type="eCH-0222:rawDataType"/>
			<xs:element name="extension" type="eCH-0155:extensionType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="delivery">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="deliveryHeader" type="eCH-0058:headerType"/>
				<xs:element name="rawDataDelivery" type="eCH-0222:eventRawDataDelivery"/>
			</xs:sequence>
			<xs:attribute ref="eCH-0222:minorVersion"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== abraxas-labs/voting-ausmittlung-service/test/Voting.Ausmittlung.Test/ImportTests/ExampleFiles/ech0222_import_ok.xml
<?xml version="1.0" encoding="utf-8"?>
<delivery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
          xmlns="http://www.ech.ch/xmlns/eCH-0222/1"
          xsi:schemaLocation="http://www.ech.ch/xmlns/eCH-0222/1 http://www.ech.ch/xmlns/eCH-0222/1/eCH-0222-1-0.xsd">
  <deliveryHeader xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.ech.ch/xmlns/eCH-0058/5 http://www.ech.ch/xmlns/eCH-0058/5/eCH-0058-5-0.xsd">
    <eCH-0058:senderId>3-CH-1</eCH-0058:senderId>
    <eCH-0058:messageId>mock-id</eCH-0058:messageId>
    <eCH-0058:messageType>eCH-0222</eCH-0058:messageType>
    <eCH-0058:sendingApplication>
      <eCH-0058:manufacturer>Abraxas Informatik AG</eCH-0058:manufacturer>
      <eCH-0058:product>VOTING Ausmittlung</eCH-0058:product>
      <eCH-0058:productVersion>DEV</eCH-0058:productVersion>
    </eCH-0058:sendingApplication>
    <eCH-0058:messageDate>2020-01-10T13:12:10.200</eCH-0058:messageDate>
    <eCH-0058:action>1</eCH-0058:action>
    <eCH-0058:testDeliveryFlag>true</eCH-0058:testDeliveryFlag>
  </deliveryHeader>
  <rawDataDelivery>
    <reportingBody>
      <reportingBodyIdentification>200</reportingBodyIdentification>
      <creationDateTime>2021-08-25T07:50:57.4477353Z</creationDateTime>
    </reportingBody>
    <rawData>
      <contestIdentification>95825eb0-0f52-461a-a5f8-23fb35fa69e1</contestIdentification>
      <countingCircleRawData>
        <countingCircleId>ca7be031-d4ce-4bb6-9538-b5e5d19e5a3e</countingCircleId>
        <electionGroupBallotRawData>
          <electionGroupIdentification>6eaa4d6b-eb0a-4315-b0b8-a68266303ab1</electionGroupIdentification>
          <electionRawData>
            <electionIdentification>d66ced3e-a2e4-4178-932b-ac91ee6a9d85</electionIdentification>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>Hans Muster</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>Hans Mueller</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>hans mueller</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>hans m√ºller</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>vereinzelt</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <candidateIdentification>be81a3f3-5a9e-4a69-8f19-4f0598a32955</candidateIdentification>
                  <candidateReferenceOnPosition>number1</candidateReferenceOnPosition>
                </candidate>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <candidateIdentification>be81a3f3-5a9e-4a69-8f19-4f0598a32955</candidateIdentification>
                  <candidateReferenceOnPosition>number1</candidateReferenceOnPosition>
                </candidate>
              </ballotPosition>
              <ballotPosition>
                <candidate>
                  <writeIn>vereinzelt</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <candidateIdentification>be81a3f3-5a9e-4a69-8f19-4f0598a32955</candidateIdentification>
                  <candidateReferenceOnPosition>number1</candidateReferenceOnPosition>
                </candidate>
              </ballotPosition>
            </ballotRawData>
          </electionRawData>
          <electionRawData>
            <electionIdentification>5ec8cf85-229a-4dc7-a601-1bb6980fee78</electionIdentification>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <candidateIdentification>6bf76024-ed15-4b7e-b68e-583b7bb5d2d5</candidateIdentification>
                  <candidateReferenceOnPosition>number1</candidateReferenceOnPosition>
                </candidate>
              </ballotPosition>
              <ballotPosition>
                <candidate>
                  <writeIn>Hans-Peter</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>Hans-Peter</writeIn>
                </candidate>
              </ballotPosition>
              <ballotPosition>
                <isEmpty>true</isEmpty>
              </ballotPosition>
            </ballotRawData>
            <ballotRawData>
              <ballotPosition>
                <candidate>
                  <writeIn>Hans-Peter</writeIn>
                </candidate>
              </ballotPosition>
            </ballotRawData>
          </electionRawData>
        </electionGroupBallotRawData>
      </countingCircleRawData>
      <countingCircleRawData>
        <countingCircleId>0bb8d89c-d387-40d0-83cf-84e118a8d524</countingCircleId>
        <voteRawData>
          <!-- this is an unknown vote ID, but the import should work nevertheless. -->
          <voteIdentification>29a239cf-40b2-4a9b-8a71-726976ec7109</voteIdentification>
          <ballotRawData>
            <ballotIdentification>154ee710-88b7-419a-ae5b-74a44c9c969e</ballotIdentification>
            <ballotCasted>
              <ballotCastedNumber>1</ballotCastedNumber>
              <questionRawData>
                <questionIdentification>1</questionIdentification>
                <casted>
                  <castedVote>1</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>2</questionIdentification>
                <casted>
                  <castedVote>2</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>tiebreak-1</questionIdentification>
                <casted>
                  <castedVote>1</castedVote>
                </casted>
              </questionRawData>
            </ballotCasted>
          </ballotRawData>
          <ballotRawData>
            <ballotIdentification>154ee710-88b7-419a-ae5b-74a44c9c969e</ballotIdentification>
            <ballotCasted>
              <ballotCastedNumber>2</ballotCastedNumber>
              <questionRawData>
                <questionIdentification>1</questionIdentification>
                <casted>
                  <castedVote>3</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>2</questionIdentification>
                <casted>
                  <castedVote>1</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>tiebreak-1</questionIdentification>
                <casted>
                  <castedVote>2</castedVote>
                </casted>
              </questionRawData>
            </ballotCasted>
          </ballotRawData>
          <ballotRawData>
            <ballotIdentification>154ee710-88b7-419a-ae5b-74a44c9c969e</ballotIdentification>
            <ballotCasted>
              <ballotCastedNumber>3</ballotCastedNumber>
              <questionRawData>
                <questionIdentification>1</questionIdentification>
                <casted>
                  <castedVote>2</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>2</questionIdentification>
                <casted>
                  <castedVote>2</castedVote>
                </casted>
              </questionRawData>
              <questionRawData>
                <questionIdentification>tiebreak-1</questionIdentification>
                <casted>
